[build]
  command = "mkdir -p scripts && cp scripts-netlify/* scripts/ && npm run build-static-html"
  publish = "public-static"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  # Note: Sensitive environment variables like DATABASE_URI, NEXTAUTH_SECRET, etc.
  # should be set in the Netlify dashboard's Environment variables section
  # and not directly in this file for security reasons

# No plugins needed for static HTML
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]
