[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "SKIP_TYPESCRIPT_CHECK=true bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"
  SKIP_TYPESCRIPT_CHECK = "true"
  DATABASE_URI = "mongodb+srv://username:password@cluster0.mongodb.net/mosque-connect?retryWrites=true&w=majority"
  GOOGLE_MAPS_API_KEY = "your-google-maps-api-key"
  NEXTAUTH_SECRET = "your-next-auth-secret"

[dev]
  command = "bun run dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"
